version: "3.9"

services:
  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    ports:
      - 5004:5000
    depends_on:
      - db

  db:
    build:
      context: ./services/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000