version: "3.9"

services:
  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    volumes:
      - "./services/backend:/usr/src/chat-app"
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/app_dev
      - FLASK_ENV=development
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_HOST=db
      - DB_NAME=postgres
      - SECRET_KEY=secret
    depends_on:
      - db

  db:
    build:
      context: ./services/db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  


  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING= true
      - NODE_ENV= development
      - REACT_APP_BACKEND_SERVICE_URL=http://localhost:5004
    volumes:
      - "./services/frontend:/usr/src/chat-app"
      - "/usr/src/chat-app/node_modules"
    depends_on:
      - backend
